name: Componente
on: workflow_dispatch
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  test:
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
  release-major:
    runs-on: ubuntu-latest
    steps:
      - run: chmod +x $HOME/bin/release.sh && $HOME/bin/release.sh --major
  release-minor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x bin/release.sh && bin/release.sh --minor
  release-patch:
    runs-on: ubuntu-latest
    steps:
      - run: ./bin/release.sh --minor

