name: Componente
on:
  pull_request:
    types: [labeled]
  workflow_dispatch: ~
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  release-major:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels, 'major')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Major
        run: chmod +x bin/release.sh && bin/release.sh --major
  release-minor:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels, 'minor')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Minor
        run: chmod +x bin/release.sh && bin/release.sh --minor
  release-patch:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels, 'patch')
    steps:
      - name: Checkout Patch
        uses: actions/checkout@v2
      - name: Release Patch
        run: chmod +x bin/release.sh && bin/release.sh --patch
