name: Componente
on:
  workflow_dispatch:
    inputs:
      release:
        description: major, minor ou patch
        required: true
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: release ${{ github.event.inputs.release }}
        run: chmod +x bin/release.sh && bin/release.sh --${{ github.event.inputs.release }}
  