name: Componente
on:
  pull_request:
    types: [labeled]
  workflow_dispatch: ~
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  test:
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release - Major
        if: contains(github.event.pull_request.labels, 'major')
        uses: actions/checkout@v2
        run: chmod +x bin/release.sh && bin/release.sh --major
      - name: Release - Minor
        if: contains(github.event.pull_request.labels, 'minor')
        uses: actions/checkout@v2
        run: chmod +x bin/release.sh && bin/release.sh --minor
      - name: Release - Patch
        if: contains(github.event.pull_request.labels, 'patch')
        uses: actions/checkout@v2
        run: chmod +x bin/release.sh && bin/release.sh --patch
  