name: Componente
on: workflow_dispatch
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
  test:
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
  release-major:
    runs-on: ubuntu-latest
    steps:
      - run: ./bin/release.sh --major
  release-minor:
    runs-on: ubuntu-latest
    steps:
      - run: ./bin/release.sh --minor
  release-patch:
    runs-on: ubuntu-latest
    steps:
      - run: ./bin/release.sh --minor

